export default (challenges = {
  大: 'big 大',
  小: 'small 小',
  中: 'middle 中',
  饭: 'rice 饭',
  面: 'noodles 面',
  肉: 'meat 肉',
  牛: 'cow 牛',
  鸡: 'chicken 鸡',
  猪: 'pig 猪',
  鞋: 'shoe 鞋',
  上: 'up 上',
  下: 'down 下',
  左: 'left 左',
  右: 'right 右',
  前: 'front 前',
  后: 'back 后',
  手: 'hand 手',
  足: 'foot 足'
})
